### ISSUE TITLE
CS171 can not load videos

### ISSUE THREAD

**Issue by Kyle-1006** [i-TechX/iTechX#101] opened 2023-10-25 07:25 UTC
Hello, I am taking CS171 course this semester and want to see lecture videos, but in 2022 Fall of CS171, all the videos are rejected to be loaded, just as the picture shows, how can i solve this?
![9_PAJV$N
T29TQ$F%64FGJ](https://github.com/i-TechX/iTechX/assets/147592464/62f3b77a-a2b7-472c-9c3a-1fc10ae00e70)

**Comment by why-in-Shanghaitech** [comment] 2023-10-25 08:13
Hi! Thank you for reaching out. Is this a duplicate of #100?

Unfortunately, the our video hosting and streaming platform, streamsb, is offline. If this won't recover, I think the videos will be lost forever. These videos were shared in old epan system in the university, which has been deprecated. The only way to access them is to contact the TAs/students of that semester, but it is highly possible that they do not have a copy either.

**Comment by Kyle-1006** [comment] 2023-10-25 10:53
Yes, I mistakely put the question on the wrong place. Thank you for your answer, I will contact them.

**Comment by why-in-Shanghaitech** [comment] 2023-11-02 12:16
> Yes, I mistakely put the question on the wrong place. Thank you for your answer, I will contact them.

Well, I prefer using Github Discussions as a QA platform. Anyway, don't mind.

**Comment by why-in-Shanghaitech** [comment] 2023-11-02 12:16
Sadly, it has been confirmed that streamsb has been closed on July 30.

https://www.wjunction.com/threads/streamsb-closes-for-good-july-30.261500/

iTechX needs to remove all video resources. See #97 for details. I'm closing this issue for now.

**Closed as completed by why-in-Shanghaitech** 2023-11-02 12:16 UTC
