### ISSUE TITLE
Maybe the discussion video links are obsolete?

### ISSUE THREAD

**Issue by itsuitsuki** [i-TechX/iTechX#97] opened 2023-10-16 10:56 UTC
![image](https://github.com/i-TechX/iTechX/assets/110326128/eea7c7cb-2c15-40d1-b7ab-6155e6a8f07a)
![image](https://github.com/i-TechX/iTechX/assets/110326128/2ff53f7e-a798-47b4-8aa4-4373a97c20e1)

Failed to load these videos no matter whether I chose to use scientific internet surfing tools. If the videos are still preserved now, may we reach the videos by some cloud drives (like Google drive)?

**Comment by itsuitsuki** [comment] 2023-10-16 10:56
The course of the screenshot is CS101 Fall 2022.

**Comment by why-in-Shanghaitech** [comment] 2023-10-16 12:09
Hi! Thank you very much for reporting this issue. It seems that our video hosting and streaming platform, streamsb, is offline. I'm not sure whether it is under temporary maintenance or shutdown forever. I'll keep an eye on this issue and see if we need to remove all the video resources.

Luckily, this does not affect much since most videos do not ever have an audience.

**Comment by why-in-Shanghaitech** [comment] 2023-11-02 12:11
Sadly, it has been confirmed that streamsb has been closed on July 30.

https://www.wjunction.com/threads/streamsb-closes-for-good-july-30.261500/

iTechX needs to remove all video resources. I am wondering how students think about re-uploading parts of the videos to other platforms. Maybe I'll make a survey later.

**Comment by why-in-Shanghaitech** [comment] 2023-11-04 06:00
Closing this issue for now. Discussions are still welcome.

**Closed as completed by why-in-Shanghaitech** 2023-11-04 06:00 UTC
